# Generated by Django 5.0.7 on 2024-07-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Empresario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('usuario', models.CharField(max_length=12, unique=True)),
                ('contraseña', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.CharField(blank=True, max_length=100)),
                ('controlde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('delCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('deCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('reactivos', models.CharField(max_length=100)),
                ('deDominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=500)),
                ('actividad', models.CharField(default='7221', max_length=4)),
                ('delEmpresario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.empresario')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=2)),
                ('reactivo', models.CharField(max_length=500)),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Likert'), (2, 'Si o No'), (3, 'Sección')], default=1)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.CharField(choices=[('1', '15 a 19'), ('2', '20 a 24'), ('3', '25 a 29'), ('4', '30 a 34'), ('5', '35 a 39'), ('6', '40 a 44'), ('7', '45 a 49'), ('8', '50 a 54'), ('9', '55 a 59'), ('A', '60 a 64'), ('B', '65 a 69'), ('C', '70 o más')], default='2', max_length=1)),
                ('nEstudios', models.CharField(choices=[('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Bachillerato o Preparatoria'), ('4', 'Técnico Superior'), ('5', 'Licenciatura'), ('6', 'Maestría'), ('7', 'Doctorado')], default='1', max_length=1)),
                ('eTerminados', models.CharField(choices=[('T', 'Terminados'), ('I', 'Inconclusos')], default='T', max_length=1)),
                ('tPuesto', models.CharField(choices=[('O', 'Operativo'), ('S', 'Supervisor'), ('P', 'Profesional o técnico'), ('G', 'Gerente')], default='o', max_length=1)),
                ('tContrato', models.CharField(choices=[('O', 'Por Obra o proyecto'), ('I', 'Tiempo indeterminado'), ('T', 'Tiempo determinado o Temporal'), ('H', 'Honorarios')], default='I', max_length=1)),
                ('tPersonal', models.CharField(choices=[('S', 'Sindicalizado'), ('C', 'Confianza'), ('N', 'Ninguno')], default='N', max_length=1)),
                ('tJornada', models.CharField(choices=[('D', 'Fijo diurno (entre las 6:00 y 20:00 hrs)'), ('N', 'Fijo nocturno (entre las 20:00 y 6:00 hrs)'), ('M', 'Fijo mixto (combinación de nocturno y diurno)')], default='D', max_length=1)),
                ('rotacion', models.BooleanField()),
                ('experiencia', models.CharField(choices=[('1', 'Menos de 6 meses'), ('2', 'Entre 6 meses y 1 año'), ('3', 'Entre 1 a 4 años'), ('4', 'Entre 5 a 9 años'), ('5', 'Entre 10 a 14 años'), ('6', 'Entre 15 a 19 años'), ('7', 'Entre 20 a 24 años'), ('8', '25 años o más')], default='3', max_length=1)),
                ('eLaboral', models.CharField(choices=[('1', 'Menos de 6 meses'), ('2', 'Entre 6 meses y 1 año'), ('3', 'Entre 1 a 4 años'), ('4', 'Entre 5 a 9 años'), ('5', 'Entre 10 a 14 años'), ('6', 'Entre 15 a 19 años'), ('7', 'Entre 20 a 24 años'), ('8', '25 años o más')], default='3', max_length=1)),
                ('trabajaEn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numEncuesta', models.SmallIntegerField()),
                ('respuestas', models.CharField(max_length=100)),
                ('delTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('deDimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.dimension')),
                ('deEncuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normales', models.CharField(max_length=200)),
                ('alReves', models.CharField(max_length=200)),
                ('delCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.cuestionario')),
            ],
        ),
    ]
