# Generated by Django 5.0.7 on 2024-07-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='empresa',
            name='calle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigoPostal',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='colonia',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('Ags', 'Aguascalientes'), ('Bc', 'Baja California'), ('Bcs', 'Baja California Sur'), ('Cam', 'Campeche'), ('Chi', 'Chiapas'), ('Chh', 'Chihuahua'), ('Cdm', 'Ciudad de México'), ('Coa', 'Coahuila'), ('Col', 'Colima'), ('Dur', 'Durango'), ('Edm', 'Estado de México'), ('Gua', 'Guanajuato'), ('Gue', 'Guerrero'), ('Hid', 'Hidalgo'), ('Jal', 'Jalisco'), ('Mic', 'Michoacán'), ('Mor', 'Morelos'), ('Nay', 'Nayarit'), ('Nl', 'Nuevo León'), ('Oax', 'Oaxaca'), ('Pue', 'Puebla'), ('Que', 'Querétaro'), ('Qro', 'Quintana Roo'), ('SLP', 'San Luis Potosí'), ('Sin', 'Sinaloa'), ('Son', 'Sonora'), ('Tab', 'Tabasco'), ('Tam', 'Tamaulipas'), ('Tla', 'Tlaxcala'), ('Ver', 'Veracruz'), ('Yuc', 'Yucatán'), ('Zac', 'Zacatecas')], default='Jal', max_length=3),
        ),
        migrations.AddField(
            model_name='empresa',
            name='interior',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='empresa',
            name='municipio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='población',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
