# Generated by Django 5.0.7 on 2024-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionarios', '0002_remove_empresa_domicilio_empresa_calle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='empresario',
            name='apellido',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empresario',
            name='usuario',
            field=models.CharField(default='usuario', max_length=12, unique=True),
        ),
    ]
