# Generated by Django 5.0.7 on 2024-08-21 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionarios', '0005_alter_trabajador_elaboral_alter_trabajador_nestudios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='delCuestionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cuestionarios.cuestionario'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='eTerminados',
            field=models.CharField(choices=[('T', 'Terminados'), ('I', 'Inconclusos')], default='I', max_length=1, verbose_name='Estudios terminados'),
        ),
    ]
