# Generated by Django 5.0.7 on 2024-08-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionarios', '0006_encuesta_delcuestionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
