# Generated by Django 5.0.7 on 2024-08-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionarios', '0008_encuesta_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='secuencia',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
