# Generated by Django 5.0.7 on 2024-08-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionarios', '0009_alter_control_secuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='secuencia',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
