# Generated by Django 5.0.7 on 2024-09-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuestionarios', '0011_categoria_alto_categoria_bajo_categoria_medio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='muyAlto',
        ),
        migrations.RemoveField(
            model_name='cuestionario',
            name='muyAlto',
        ),
        migrations.RemoveField(
            model_name='dominio',
            name='muyAlto',
        ),
    ]
